/**
 * Generates src/theme.css (the web's Tailwind @theme block + chart chrome
 * vars) from packages/core/theme.ts, so web and mobile share one token
 * source. Run via `npm run gen:theme` after changing theme.ts; the output is
 * committed. Node strips the .ts types natively, so there's no build step.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const { fonts, cream, linen, forest, honey, chartChrome } = await import(
  '../packages/core/theme.ts'
)

const ramp = (name, colors) =>
  Object.entries(colors)
    .map(([step, hex]) => `  --color-${name}-${step}: ${hex};`)
    .join('\n')

const css = `/*
 * GENERATED by scripts/gen-theme.mjs from packages/core/theme.ts — do not
 * edit by hand; change theme.ts and run \`npm run gen:theme\`.
 */
@theme {
  --font-sans: ${fonts.sans};
  --font-display: ${fonts.display};

  --color-cream: ${cream};

${ramp('linen', linen)}

${ramp('forest', forest)}

${ramp('honey', honey)}
}

/*
 * Chart chrome (gridlines, axis ticks, hover cursor) — plain vars, not @theme,
 * because they flip with dark mode. Recharts reads them via var() in SVG props.
 */
:root {
  --chart-grid: ${chartChrome.light.grid};
  --chart-tick: ${chartChrome.light.tick};
  --chart-cursor: ${chartChrome.light.cursor};
}
.dark {
  --chart-grid: ${chartChrome.dark.grid};
  --chart-tick: ${chartChrome.dark.tick};
  --chart-cursor: ${chartChrome.dark.cursor};
}
`

const out = fileURLToPath(new URL('../src/theme.css', import.meta.url))
writeFileSync(out, css)
console.log(`wrote ${out}`)
